export { default as Hero } from "./Hero";
export { default as Integrations } from "./Integrations";
export { default as Features } from "./Features";
export { default as Automation } from "./Automation";
export { default as AIAssistant } from "./AIAssistant";
export { default as Pricing } from "./Pricing";
export { default as Testimonials } from "./Testimonials";
export { default as FAQ } from "./FAQ";
export { default as CTA } from "./CTA";
